// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiNEsWbgeNd5lL_fSqSd6GtTaASmH8XZM',
    appId: '1:287505932801:web:0da91e0e72374bcd085600',
    messagingSenderId: '287505932801',
    projectId: 'donor-proj',
    authDomain: 'donor-proj.firebaseapp.com',
    storageBucket: 'donor-proj.firebasestorage.app',
    measurementId: 'G-HCW7EXFRW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsVhuT1MVqu0UikAaTeWRulQCaELfW8Y',
    appId: '1:287505932801:android:2319e9a52186351a085600',
    messagingSenderId: '287505932801',
    projectId: 'donor-proj',
    storageBucket: 'donor-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMLZ0zyMzVK6WKvDx_L56D6sfBWf3KNdE',
    appId: '1:287505932801:ios:b6535551dc8b6988085600',
    messagingSenderId: '287505932801',
    projectId: 'donor-proj',
    storageBucket: 'donor-proj.firebasestorage.app',
    iosBundleId: 'com.example.clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMLZ0zyMzVK6WKvDx_L56D6sfBWf3KNdE',
    appId: '1:287505932801:ios:b6535551dc8b6988085600',
    messagingSenderId: '287505932801',
    projectId: 'donor-proj',
    storageBucket: 'donor-proj.firebasestorage.app',
    iosBundleId: 'com.example.clone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiNEsWbgeNd5lL_fSqSd6GtTaASmH8XZM',
    appId: '1:287505932801:web:a4e3e59166107036085600',
    messagingSenderId: '287505932801',
    projectId: 'donor-proj',
    authDomain: 'donor-proj.firebaseapp.com',
    storageBucket: 'donor-proj.firebasestorage.app',
    measurementId: 'G-MMRKEVJ41Y',
  );
}
